name: Update README with Calendar

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

      - name: Commit metrics
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add metrics.plugin.isocalendar.svg
          git commit -m "Update isocalendar" || echo "No changes to commit"
          git push
